apiVersion: v1
kind: Service
metadata:
  name: relayhorizon
  namespace: relayhorizon
  labels:
    app: relayhorizon
spec:
  selector:
    app: relayhorizon
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  type: ClusterIP